.TH "core/client.c" 3 "Fri Mar 1 2013" "Crayon Physics A++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/client.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'client\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBclient_socket_connect\fP (char *server, int port)"
.br
.ti -1c
.RI "char * \fBclient_recv\fP (int sockfd, char *buf)"
.br
.ti -1c
.RI "int \fBclient_send\fP (int sockfd, char *buf)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* client_recv (intsockfd, char *buf)"

.PP
Definition at line 111 of file client\&.c\&.
.SS "int client_send (intsockfd, char *buf)"

.PP
Definition at line 123 of file client\&.c\&.
.SS "int client_socket_connect (char *server, intport)"

.PP
Definition at line 88 of file client\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Crayon Physics A++ from the source code\&.
