.TH "gui" 3 "Fri Mar 1 2013" "Crayon Physics A++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gui \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gui\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "GtkWidget * \fBwindow\fP"
.br
.ti -1c
.RI "GtkWidget * \fBdraw_area\fP"
.br
.ti -1c
.RI "GtkWidget * \fBentry\fP"
.br
.ti -1c
.RI "GtkWidget * \fBtext_view\fP"
.br
.ti -1c
.RI "GtkTextMark * \fBmark\fP"
.br
.ti -1c
.RI "cpSpace * \fBspace\fP"
.br
.ti -1c
.RI "cpBody * \fBcurrent_body\fP"
.br
.ti -1c
.RI "int \fBsockfd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file gui\&.h\&.
.SH "Field Documentation"
.PP 
.SS "cpBody* gui::current_body"

.PP
Definition at line 23 of file gui\&.h\&.
.SS "GtkWidget* gui::draw_area"

.PP
Definition at line 18 of file gui\&.h\&.
.SS "GtkWidget* gui::entry"

.PP
Definition at line 19 of file gui\&.h\&.
.SS "GtkTextMark* gui::mark"

.PP
Definition at line 21 of file gui\&.h\&.
.SS "int gui::sockfd"

.PP
Definition at line 24 of file gui\&.h\&.
.SS "cpSpace* gui::space"

.PP
Definition at line 22 of file gui\&.h\&.
.SS "GtkWidget* gui::text_view"

.PP
Definition at line 20 of file gui\&.h\&.
.SS "GtkWidget* gui::window"

.PP
Definition at line 17 of file gui\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Crayon Physics A++ from the source code\&.
